<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LPT-ADRIDI" failures="2" tests="3" name="runners.TestRunner" time="64.693" errors="0" timestamp="2024-09-02T21:52:11 CET" skipped="0">
  <testcase classname="runners.TestRunner" name="runScenario" time="18.059">
    <failure message="Seems like you are not logged in expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Seems like you are not logged in expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.BackgroundSteps.user_is_navigated_to_cars_collection(BackgroundSteps.java:61)
at ✽.user is navigated to cars collection(file:///home/ala/eclipse-workspace/ADExoticsCarRentalTesting-Cucumber-Selenium/src/test/resources/features/login.feature:55)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runners.TestRunner" name="runScenario" time="26.881">
    <failure message="Seems like you are not logged in expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Seems like you are not logged in expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinitions.BackgroundSteps.user_is_navigated_to_cars_collection(BackgroundSteps.java:61)
at ✽.user is navigated to cars collection(file:///home/ala/eclipse-workspace/ADExoticsCarRentalTesting-Cucumber-Selenium/src/test/resources/features/login.feature:55)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runners.TestRunner" name="runScenario" time="19.753"/>
</testsuite> <!-- runners.TestRunner -->
